name: Check health of libraries (public deps)

on:
  workflow_dispatch:
    inputs:
      commitsha:
        description: "Commit SHA for the release (if blank use latest on this branch)"

env:
  commitsha: "${{ github.event.inputs.commitsha || github.sha }}"
  NODE_VERSION: 18.17.x

jobs:
  build-using-public-deps:
    # if: github.repository == 'EpicGamesExt/PixelStreamingInfrastructure'
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.set_output.outputs.continue }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        ref: "${{ env.commitsha }}"

    - uses: actions/setup-node@v4
      with:
        node-version: "${{ env.NODE_VERSION }}"
        registry-url: 'https://registry.npmjs.org'

    - name: Remove NPM workspaces
      run: rm package.json && rm package-lock.json

    - name: Build signalling using published packages only
      if: always()
      working-directory: Signalling
      run: npm install && npm run build && npm run lint
    - name: Build Wilbur using published packages only
      if: always()
      working-directory: SignallingWebServer
      run: npm install && npm run build && npm run lint
    - name: Build Frontend/library using published packages only
      if: always()
      working-directory: Frontend/library
      run: npm install && npm run build && npm run lint && npm run test
    - name: Build Frontend/ui-library using published packages only
      if: always()
      working-directory: Frontend/ui-library
      run: npm install && npm run build && npm run lint
    - name: Build Frontend/implementations/typescript using published packages only
      if: always()
      working-directory: Frontend/implementations/typescript
      run: npm install && npm run build

    - id: set_output
      run: echo "continue=true" >> $GITHUB_ENV

