name: Check health of libraries (public deps)

on:
  workflow_dispatch:
  push:
    paths:
      - "Common/**"
      - "Signalling/**"
      - "SignallingWebServer/**"
      - "Frontend/library/**"
      - "Frontend/ui-library/**"
      - "Frontend/implementations/typescript/**"
  pull_request:
    paths:
      - "Common/**"
      - "Signalling/**"
      - "SignallingWebServer/**"
      - "Frontend/library/**"
      - "Frontend/ui-library/**"
      - "Frontend/implementations/typescript/**"

env:
  NODE_VERSION: 18.17.x

jobs:
  check-if-bypass:
      runs-on: ubuntu-latest
      outputs:
        bypass: ${{ steps.checkbypass.outputs.bypass }}
      steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 5  # This should be enough history to contain the commit that triggered the PR

      - name: Check PR body for bypass-publish-check
        if: github.event_name == 'pull_request'
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: echo "BODY_CHECK=\"$PR_BODY\"" >> $GITHUB_ENV

      - name: Check commit message for push event
        if: github.event_name == 'push'
        env:
          COMMIT: ${{ github.event.head_commit.message }}
        run: echo "BODY_CHECK=\"$COMMIT\"" >> $GITHUB_ENV

      - name: Check commit message for bypass
        id: checkbypass
        run: |
          if echo "$BODY_CHECK" | grep -q "#bypass-publish-check"; then
            echo "bypass=true" >> $GITHUB_OUTPUT
            echo "bypass=true"
          else
            echo "bypass=false" >> $GITHUB_OUTPUT
            echo "bypass=flase"
          fi

  build-using-public-deps:
      needs: check-if-bypass
      if: github.repository == 'EpicGamesExt/PixelStreamingInfrastructure' && needs.check-if-bypass.outputs.bypass == 'false' # Only run if bypass is false
      runs-on: ubuntu-latest
      steps:

      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"
          registry-url: 'https://registry.npmjs.org'

      - name: Remove NPM workspaces
        run: rm package.json && rm package-lock.json

      - name: Build signalling using published packages only
        if: always()
        working-directory: Signalling
        run: npm install && npm run build && npm run lint

      - name: Build Wilbur using published packages only
        if: always()
        working-directory: SignallingWebServer
        run: npm install && npm run build && npm run lint

      - name: Build Frontend/library using published packages only
        if: always()
        working-directory: Frontend/library
        run: npm install && npm run build && npm run lint && npm run test

      - name: Build Frontend/ui-library using published packages only
        if: always()
        working-directory: Frontend/ui-library
        run: npm install && npm run build && npm run lint

      - name: Build Frontend/implementations/typescript using published packages only
        if: always()
        working-directory: Frontend/implementations/typescript
        run: npm install && npm run build
