name: Publish common lib
on:
  workflow_dispatch:
  push:
    # branches: ['UE5.5']
    paths: ['Common/package.json']

env:
  NODE_VERSION: 18.17.x

jobs:
  build:
    # if: github.repository == 'EpicGamesExt/PixelStreamingInfrastructure'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Common
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'Common'
          sparse-checkout-cone-mode: false
        
      - run: |
          package_content=`cat package.json`
          package_content="${package_content//'%'/'%25'}"
          package_content="${package_content//$'\n'/'%0A'}"
          package_content="${package_content//$'\r'/'%0D'}"
          echo "json=${{ fromJson($package_content).version }}"
          # echo "json=$package_content" >> $GITHUB_ENV
          
      - name: Extract library version
        id: get-version
        run: |
          echo "VERSION=${{ fromJson(env.json).version }}"

      # - name: Check version
      #   run: |
      #     echo ${{ steps.get-version.outputs.version }}

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: "${{ env.NODE_VERSION }}"
      #     registry-url: 'https://registry.npmjs.org'
      # - run: npm install
      # - run: npm run build
      # - run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
