name: Publish SFU image

on:
  workflow_dispatch:
  push:
    branches: ['UE5.5']
    paths: ['SFU/package.json']

jobs:
  signalling-server-image:
    if: github.repository == 'EpicGamesExt/PixelStreamingInfrastructure'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            sparse-checkout: 'SFU'
            sparse-checkout-cone-mode: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: pixelstreamingunofficial
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the SFU container image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: 'pixelstreamingunofficial/pixel-streaming-sfu:5.5'
          push: true
          file: SFU/Dockerfile
        
      - id: get-package-json
        run: |
          package_content=`cat SFU/package.json`
          echo "json<<EOF" >> $GITHUB_OUTPUT
          echo $package_content >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - shell: bash
        id: extract_branch
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/sfu-${{ steps.extract_branch.outputs.branch }}-${{ fromJson(steps.get-package-json.outputs.json).version }}',
              sha: context.sha
            })
